/**
 * 常量定义
 */
export const USER_ROLES = {
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  STUDENT_ADMIN: 'STUDENT_ADMIN',
  COLLEGE_ADMIN: 'COLLEGE_ADMIN',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN'
}

export const SPACE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  MAINTENANCE: 'MAINTENANCE',
  DISABLED: 'DISABLED'
}

export const RESERVATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
}

export const ACTIVITY_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
}

export const NEWS_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PUBLISHED: 'PUBLISHED',
  REJECTED: 'REJECTED'
}

export const ENTRY_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ENTERED: 'ENTERED',
  EXITED: 'EXITED'
}

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
}

/**
 * 状态文本映射
 */
export const STATUS_TEXT = {
  [SPACE_STATUS.AVAILABLE]: '可用',
  [SPACE_STATUS.MAINTENANCE]: '维护中',
  [SPACE_STATUS.DISABLED]: '已禁用',
  [RESERVATION_STATUS.PENDING]: '待审核',
  [RESERVATION_STATUS.APPROVED]: '已通过',
  [RESERVATION_STATUS.REJECTED]: '已拒绝',
  [RESERVATION_STATUS.CANCELLED]: '已取消',
  [RESERVATION_STATUS.COMPLETED]: '已完成',
  [ACTIVITY_STATUS.DRAFT]: '草稿',
  [ACTIVITY_STATUS.SUBMITTED]: '已提交',
  [ACTIVITY_STATUS.APPROVED]: '已通过',
  [ACTIVITY_STATUS.REJECTED]: '已拒绝',
  [ACTIVITY_STATUS.PUBLISHED]: '已发布',
  [ACTIVITY_STATUS.ONGOING]: '进行中',
  [ACTIVITY_STATUS.COMPLETED]: '已完成',
  [ACTIVITY_STATUS.CANCELLED]: '已取消',
  [NEWS_STATUS.DRAFT]: '草稿',
  [NEWS_STATUS.PENDING]: '待审核',
  [NEWS_STATUS.PUBLISHED]: '已发布',
  [NEWS_STATUS.REJECTED]: '已驳回',
  [ENTRY_STATUS.DRAFT]: '草稿',
  [ENTRY_STATUS.PENDING]: '待审核',
  [ENTRY_STATUS.APPROVED]: '已通过',
  [ENTRY_STATUS.REJECTED]: '已驳回',
  [ENTRY_STATUS.ENTERED]: '已入驻',
  [ENTRY_STATUS.EXITED]: '已退出',
  [APPROVAL_STATUS.PENDING]: '待审批',
  [APPROVAL_STATUS.APPROVED]: '已通过',
  [APPROVAL_STATUS.REJECTED]: '已拒绝'
}

/**
 * 状态类型映射（用于 Element Plus Tag 组件）
 */
export const STATUS_TYPE = {
  [SPACE_STATUS.AVAILABLE]: 'success',
  [SPACE_STATUS.MAINTENANCE]: 'warning',
  [SPACE_STATUS.DISABLED]: 'danger',
  [RESERVATION_STATUS.PENDING]: 'warning',
  [RESERVATION_STATUS.APPROVED]: 'success',
  [RESERVATION_STATUS.REJECTED]: 'danger',
  [RESERVATION_STATUS.CANCELLED]: 'info',
  [RESERVATION_STATUS.COMPLETED]: 'success',
  [ACTIVITY_STATUS.DRAFT]: 'info',
  [ACTIVITY_STATUS.SUBMITTED]: 'warning',
  [ACTIVITY_STATUS.APPROVED]: 'success',
  [ACTIVITY_STATUS.REJECTED]: 'danger',
  [ACTIVITY_STATUS.PUBLISHED]: 'success',
  [ACTIVITY_STATUS.ONGOING]: '',
  [ACTIVITY_STATUS.COMPLETED]: 'success',
  [ACTIVITY_STATUS.CANCELLED]: 'info',
  [NEWS_STATUS.DRAFT]: 'info',
  [NEWS_STATUS.PENDING]: 'warning',
  [NEWS_STATUS.PUBLISHED]: 'success',
  [NEWS_STATUS.REJECTED]: 'danger',
  [ENTRY_STATUS.DRAFT]: 'info',
  [ENTRY_STATUS.PENDING]: 'warning',
  [ENTRY_STATUS.APPROVED]: 'success',
  [ENTRY_STATUS.REJECTED]: 'danger',
  [ENTRY_STATUS.ENTERED]: 'success',
  [ENTRY_STATUS.EXITED]: 'info',
  [APPROVAL_STATUS.PENDING]: 'warning',
  [APPROVAL_STATUS.APPROVED]: 'success',
  [APPROVAL_STATUS.REJECTED]: 'danger'
}
